### PR TITLE
No longer trying OpenMP build on MSVC

### PR DESCRIPTION
**Pull request by tay10r**
MSVC only supports OpenMP 2.0, so the build fails in a couple of spots. This commit disables OpenMP when MSVC is detected by CMake.

### CODE REVIEW

**Comment by madmann91** [comment]
It would be better though to know which spots so that I can disable the relevant bits... Just copy and paste the error log of MSVC if you have the time (I don't have it myself), I'll try and disable the parts that cause the issues you are seeing.

**Comment by tay10r** [comment]
Okay, I'll follow up with another commit.

**Comment by tay10r** [comment]
I misread your message earlier. Here's the copy and pasted error log.

```
Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  benchmark.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/binned_sah_builder.hpp(165,1): error C3001:  'taskloop': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/binned_sah_builder.hpp(221): message :  see reference to class template instantiation 'bvh::BinnedSahBuildTask<Bvh,BinCount>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/binned_sah_builder.hpp(193,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214,2): warning C4099:  'bvh::SweepSahBuildTask': type name first seen using 'class' now seen using 'struct' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(14): message :  see declaration of 'bvh::SweepSahBuildTask' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(148,1): error C3001:  'taskloop': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214): message :  see reference to class template instantiation 'bvh::SweepSahBuildTask<Bvh>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(179,1): error C3001:  'taskgroup': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(181,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(183,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(185,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(190,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(199,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/edge_volume_heuristic.hpp(49,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/edge_volume_heuristic.hpp(130): message :  see reference to class template instantiation 'bvh::EdgeVolumeHeuristic<Triangle>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
  custom_intersector.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214,2): warning C4099:  'bvh::SweepSahBuildTask': type name first seen using 'class' now seen using 'struct' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(14): message :  see declaration of 'bvh::SweepSahBuildTask' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(148,1): error C3001:  'taskloop': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214): message :  see reference to class template instantiation 'bvh::SweepSahBuildTask<Bvh>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(179,1): error C3001:  'taskgroup': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(181,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(183,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(185,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(190,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(199,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
  custom_primitive.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214,2): warning C4099:  'bvh::SweepSahBuildTask': type name first seen using 'class' now seen using 'struct' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(14): message :  see declaration of 'bvh::SweepSahBuildTask' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(148,1): error C3001:  'taskloop': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214): message :  see reference to class template instantiation 'bvh::SweepSahBuildTask<Bvh>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(179,1): error C3001:  'taskgroup': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(181,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(183,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(185,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(190,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(199,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
  simple_example.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214,2): warning C4099:  'bvh::SweepSahBuildTask': type name first seen using 'class' now seen using 'struct' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(14): message :  see declaration of 'bvh::SweepSahBuildTask' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(148,1): error C3001:  'taskloop': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(214): message :  see reference to class template instantiation 'bvh::SweepSahBuildTask<Bvh>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(179,1): error C3001:  'taskgroup': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(181,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(183,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(185,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(190,1): error C3001:  'task': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/sweep_sah_builder.hpp(199,1): error C3005:  'capture': unexpected token encountered on OpenMP 'atomic' directive [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
```

**Comment by madmann91** [comment]
I've tried to fix this in a7c6f968136ff15baa2e9d2067891d2df972e455, let me know if it does not work for you.

**Comment by tay10r** [comment]
Here's the latest error log. There still seems to be some issues.

Personally, I don't care much for Microsoft's compiler builds. I run Windows in a VM with MSVC installed just so that I know my other projects will compile if someone tries to run them with Visual Studio. Not sure if that makes a difference or not, but just an FYI.

Have you used AppVeyor before? It supports automated CI pipelines for Windows and Ubuntu. I think Travis CI has experimental Windows support last time I checked as well.

```
Microsoft (R) Build Engine version 16.2.37902+b5aaefc9f for .NET Framework
Copyright (C) Microsoft Corporation. All rights reserved.

  benchmark.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(59,38): warning C4244:  '=': conversion from 'float' to '_Ty', possible loss of data [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(59,38): warning C4244:         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(59,38): warning C4244:         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(59,38): warning C4244:             _Ty=size_t [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(59,38): warning C4244:         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :  while compiling class template member function 'std::tuple<size_t,std::unique_ptr<bvh::BoundingBox<Scalar> [],std::default_delete<_Ty>>,std::unique_ptr<bvh::Vector<Scalar,3> [],std::default_delete<bvh::Vector<Scalar,3>[]>>> bvh::HeuristicPrimitiveSplitter<Triangle>::split(const bvh::BoundingBox<Scalar> &,const Primitive *,size_t,float)' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :             _Ty=bvh::BoundingBox<Scalar> [], [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :             Primitive=Triangle [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(41): message :         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :  see reference to function template instantiation 'std::tuple<size_t,std::unique_ptr<bvh::BoundingBox<Scalar> [],std::default_delete<_Ty>>,std::unique_ptr<bvh::Vector<Scalar,3> [],std::default_delete<bvh::Vector<Scalar,3>[]>>> bvh::HeuristicPrimitiveSplitter<Triangle>::split(const bvh::BoundingBox<Scalar> &,const Primitive *,size_t,float)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :             _Ty=bvh::BoundingBox<Scalar> [], [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :             Primitive=Triangle [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(357): message :         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(355): message :  see reference to class template instantiation 'bvh::HeuristicPrimitiveSplitter<Triangle>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(117,39): warning C4244:  'initializing': conversion from 'Scalar' to 'size_t', possible loss of data [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(117,39): warning C4244:         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(117,39): warning C4244:         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(117,39): warning C4244:             Scalar=Scalar [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/heuristic_primitive_splitter.hpp(117,39): warning C4244:         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(153,1): warning C4267:  '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(124): message :  while compiling class template member function 'void bvh::LinearBvhBuilder<Bvh,Morton>::build(const bvh::BoundingBox<Scalar> &,const bvh::BoundingBox<Scalar> *,const bvh::Vector<Scalar,3> *,size_t)' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(302): message :  see reference to function template instantiation 'void bvh::LinearBvhBuilder<Bvh,Morton>::build(const bvh::BoundingBox<Scalar> &,const bvh::BoundingBox<Scalar> *,const bvh::Vector<Scalar,3> *,size_t)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(301): message :  see reference to class template instantiation 'bvh::LinearBvhBuilder<Bvh,Morton>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(159,1): warning C4267:  '=': conversion from 'size_t' to '_Ty', possible loss of data [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(159,1): warning C4267:         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(159,1): warning C4267:         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(159,1): warning C4267:             _Ty=unsigned char [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/linear_bvh_builder.hpp(159,1): warning C4267:         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/locally_ordered_clustering_builder.hpp(159,1): warning C4267:  '=': conversion from 'size_t' to 'unsigned int', possible loss of data [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/locally_ordered_clustering_builder.hpp(139): message :  while compiling class template member function 'void bvh::LocallyOrderedClusteringBuilder<Bvh,Morton>::build(const bvh::BoundingBox<Scalar> &,const bvh::BoundingBox<Scalar> *,const bvh::Vector<Scalar,3> *,size_t)' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(296): message :  see reference to function template instantiation 'void bvh::LocallyOrderedClusteringBuilder<Bvh,Morton>::build(const bvh::BoundingBox<Scalar> &,const bvh::BoundingBox<Scalar> *,const bvh::Vector<Scalar,3> *,size_t)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(295): message :  see reference to class template instantiation 'bvh::LocallyOrderedClusteringBuilder<Bvh,Morton>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/prefix_sum.hpp(15,19): error C3861:  'omp_get_level': identifier not found [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/prefix_sum.hpp(15): message :  while compiling class template member function 'bvh::PrefixSum<size_t>::PrefixSum(void)' [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\benchmark.cpp(398): message :  see reference to function template instantiation 'bvh::PrefixSum<size_t>::PrefixSum(void)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/locally_ordered_clustering_builder.hpp(30): message :  see reference to class template instantiation 'bvh::PrefixSum<size_t>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/locally_ordered_clustering_builder.hpp(182): message :  see reference to class template instantiation 'bvh::LocallyOrderedClusteringBuilder<Bvh,Morton>' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_benchmark.vcxproj]
  custom_intersector.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(100,1): error C3001:  'declare': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\custom_intersector.cpp(56): message :  see reference to function template instantiation 'bvh::BoundingBox<Scalar> bvh::compute_bounding_boxes_union<Scalar>(const bvh::BoundingBox<Scalar> *,size_t)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(104,1): error C3036:  'bbox_extend': invalid operator token in OpenMP 'reduction' clause [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_intersector.vcxproj]
  custom_primitive.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(100,1): error C3001:  'declare': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\custom_primitive.cpp(59): message :  see reference to function template instantiation 'bvh::BoundingBox<Scalar> bvh::compute_bounding_boxes_union<Scalar>(const bvh::BoundingBox<Scalar> *,size_t)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(104,1): error C3036:  'bbox_extend': invalid operator token in OpenMP 'reduction' clause [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_custom_primitive.vcxproj]
  simple_example.cpp
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(100,1): error C3001:  'declare': expected an OpenMP directive name [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\simple_example.cpp(37): message :  see reference to function template instantiation 'bvh::BoundingBox<Scalar> bvh::compute_bounding_boxes_union<Scalar>(const bvh::BoundingBox<Scalar> *,size_t)' being compiled [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\simple_example.cpp(37): message :         with [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\simple_example.cpp(37): message :         [ [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\simple_example.cpp(37): message :             Scalar=Scalar [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\test\simple_example.cpp(37): message :         ] [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
C:\Users\tay10r\Documents\Programming\bvh\include\bvh/utilities.hpp(104,1): error C3036:  'bbox_extend': invalid operator token in OpenMP 'reduction' clause [C:\Users\tay10r\Documents\Programming\bvh\build\test\bvh_simple_example.vcxproj]
```

**Comment by madmann91** [comment]
Good point about CI. I'll set this up, this will avoid exchanging things back and forth. Thank you for your help!

**Comment by tay10r** [comment]
No problem! Unfortunately there's like I can do other than help with the build system. I have absolutely zero knowledge on openmp

**Pull request merged**
