### PR TITLE
Forward Declarations

### PR DESCRIPTION
**Pull request by tay10r**
Helps reduce compile times when common classes are used in header files.

### CODE REVIEW

**Comment by madmann91** [comment]
Hello! I am not too keen on merging this right now, because of the following reasons:

- For consistency, the name of that header should be the full `forward.hpp` instead of `fwd.hpp`,
- There is no test that makes sure the forward declarations match their definitions. Adding the following to the benchmark tool would do it (before all other bvh-related includes):

```cpp
// Ensure the consistency between the forward declarations and the actual definitions
#include <bvh/forward.hpp>
```

**Comment by tay10r** [comment]
I've made adjustments based on your feedback. I added a script for generating the forward declarations, so it's easier maintaining the file for all classes. I'll be happy to update the PR if you have more feedback.

**Comment by madmann91** [comment]
I'm not too fond of having a script with a custom regex generate that file. It's a bit dangerous, because of possible unforeseen cases that the regex doesn't catch. Additionally, this script is bash only, meaning that Windows users would have to use Cygwin or something like that to get it to work. On the other hand, maintaining a long list of forwarded declarations manually is also dangerous, since I would have to manually check that every forwarded class/struct is actually implemented everytime I rename something, and so on.

If compilation times are a problem, I recommend to use the Pimpl idiom. That's what I do for my own renderer and it works nicely, without having to forward declare anything. If there's anything I can do to help you or anyone else go in that direction, let me know (including writing docs, maybe?).

If you _absolutely_ want to have that feature generated by a script, it makes sense to use a CMake script for that, as I don't want to add yet another dependency (even an optional one). It might be a bit more annoying but I know CMake has regex and file support, so I think it's doable. So, I suggest the following compromise: If you get that same behavior with a CMake script instead of a bash script, I'll merge it into master.

**Comment by tay10r** [comment]
I use PIMPL in most projects, but still need to pass some types via function parameters.

Transitioning to CMake shouldn't be an issue, CMake has good regex support. With CMake, you can create a test program with strong compiler warnings that will catch mistyped forward declarations in Travis CI. I usually use strong compiler warnings by default, so I forgot to check if they were getting used.

Of course, if this sounds like too much maintenance work, I can just stick with the header I have in my project that has the forward declarations there.

**Comment by madmann91** [comment]
That's up to you, really. I also don't want to put on you the burden of implementing that with CMake.

**Comment by tay10r** [comment]
Sorry for the delay! I think I'm going to throw in the towel for this one. I never did try the CMake script but if I ever try to give this a shot again, I'll take that approach. Thanks for the help!

**Pull request closed without merging**
